"""add email classification fields

Revision ID: a24398e5d6d6
Revises: 6bae0d65624d
Create Date: 2026-03-30 17:35:59.223323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a24398e5d6d6'
down_revision: Union[str, None] = '6bae0d65624d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('email_messages', sa.Column('extracted_company', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('email_messages', sa.Column('extracted_position', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('email_messages', sa.Column('is_dismissed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'is_dismissed')
    op.drop_column('email_messages', 'extracted_position')
    op.drop_column('email_messages', 'extracted_company')
    op.drop_column('email_messages', 'intent')
    # ### end Alembic commands ###
