"""add email client fields

Revision ID: e4edb434b899
Revises: a24398e5d6d6
Create Date: 2026-03-30 19:28:31.855265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4edb434b899'
down_revision: Union[str, None] = 'a24398e5d6d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_accounts', sa.Column('last_history_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('email_messages', sa.Column('to_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('email_messages', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('email_messages', sa.Column('body_text', sa.Text(), nullable=True))
    op.add_column('email_messages', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('email_messages', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('email_messages', sa.Column('is_job_related', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'is_job_related')
    op.drop_column('email_messages', 'is_read')
    op.drop_column('email_messages', 'label')
    op.drop_column('email_messages', 'body_text')
    op.drop_column('email_messages', 'body_html')
    op.drop_column('email_messages', 'to_address')
    op.drop_column('email_accounts', 'last_history_id')
    # ### end Alembic commands ###
